# Generated by Django 4.2.3 on 2023-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='barg', max_length=250, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
