# Generated by Django 4.2.3 on 2023-07-31 22:00

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('email', models.EmailField(max_length=250, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='پیام')),
                ('create', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')),
                ('send_mail', models.BooleanField(default=False, verbose_name='ارسال ایمیل')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['-create'],
                'indexes': [models.Index(fields=['-create'], name='blog_commen_create_9bdc05_idx')],
            },
        ),
    ]
