# Generated by Django 4.2.3 on 2023-08-16 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_image_image_file_remove_post_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('bio', models.TextField(verbose_name='بایو')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=60, scale=None, size=[500, 500], upload_to='profile_images/', verbose_name='تصویر')),
                ('job', models.CharField(max_length=250, verbose_name='شغل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='اکانت')),
            ],
        ),
    ]
