# Generated by Django 4.2.3 on 2023-08-17 16:00

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت ها'},
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
